### PR TITLE
chore: Adds whitespace lint check

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

Adds the `whitespace` lint check and make the appropriate changes to satisfy it.

### CODE REVIEW

**Comment by gab-arrobo** [comment]
ok to test

**Comment by gab-arrobo** [comment]
please rebase your PR. Thanks!

**Comment by gruyaume** [comment]
> please rebase your PR. Thanks!

Done!

**Review by gab-arrobo — APPROVED** [review]
+1

**Pull request merged**
