### PR TITLE
fix: Disable all linters

### PR DESCRIPTION
**Pull request by gatici**
- This PR disables the linters which are failing during execution. 
- The aim is fixing the SMF CI, then problems of each type of linter is being fixed in separate PR's.
-  A typecheck problem is fixed as it still appears after disabling typecheck in golanci.yml.

### CODE REVIEW

**Review by ghislainbourgeois — APPROVED** [review]

**Comment by thakurajayL** [comment]
Do you need this to be reviewed ?

**Comment by gatici** [comment]
> Do you need this to be reviewed ?

You can review if you want. Thank you!

**Comment by gab-arrobo** [comment]
test this please

**Comment by gab-arrobo** [comment]
retest this please

**Review by gab-arrobo — APPROVED** [review]
+1 (tested changes with `run-aiab`)

**Pull request merged**
