### PR TITLE
Bumps go version to 1.21 (latest stable)

### PR DESCRIPTION
**Pull request by gatici**
This project currently uses Go 1.16 which is end of life. This PR bumps the go version to 1.21 which is the latest stable release. 

The update is accomplished by running following commands:
```
go mod edit -go=1.21
go mod tidy
```

Reference: https://tip.golang.org/doc/go1.21

### CODE REVIEW

**Comment by gatici** [comment]
This PR is tested by building new image and deploying [sdcore-bundle](https://canonical-charmed-5g.readthedocs-hosted.com/en/latest/tutorial/02_deploy_sdcore/) successfully.

**Review by thakurajayL — APPROVED** [review]

**Comment by gatici** [comment]
Note: PR: https://github.com/omec-project/smf/pull/182 disables the golint checks temporarily to make the CI pass.

**Comment by dafATonf** [comment]
test this please

**Comment by gatici** [comment]
> test this please

Hello @dafATonf 
This PR is tested by building new image and deploying [sdcore-bundle](https://canonical-charmed-5g.readthedocs-hosted.com/en/latest/tutorial/02_deploy_sdcore/) successfully.

**Review by thakurajayL — APPROVED** [review]

**Comment by gab-arrobo** [comment]
test this please

**Review by gab-arrobo — APPROVED** [review]
+1 (manually tested changes with AiaB)

**Comment by gab-arrobo** [comment]
@gatici, would it be possible that you also bump up the go version for the `upfadapter` (it is a directory inside this repo that also has a go.mod file, https://github.com/omec-project/smf/blob/master/upfadapter/go.mod)?

**Pull request merged**
